modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/ChilledMaple" # URL HERE
credits = "https://github.com/ChilledMaple" # Your name here
authors = "https://github.com/ChilledMaple" # Your name here
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "pixelmon"
mandatory = true
versionRange = "[${pixelmon_version},)"
ordering = "NONE"
side = "BOTH"